---
# tasks file for Autoheal
  - name: Restart post_db services
    command: docker start docker_post_db_1
    when: '"post" in node'

  - name: Restart service
    command: docker start docker_{{ node }}_1


