---
# tasks file for Autoheal
  - name: Restart service
    command: docker start docker_{{ node }}_1

  - name: Restart post services
    command: docker start docker_post_db_1; docker start docker_{{ node }}_1
    when: "{{ 'post' in node}}"

